// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2bW5bGLSwLl3wO4sbIeCJht4IgQ2cxSo',
    appId: '1:578204003859:web:8c061510250e6d10aad9e6',
    messagingSenderId: '578204003859',
    projectId: 'jq4b-eih-2024-inv-15307',
    authDomain: 'jq4b-eih-2024-inv-15307.firebaseapp.com',
    storageBucket: 'jq4b-eih-2024-inv-15307.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXk1g2XErXMg5s-qc9VW4ii5qxCOIdY2E',
    appId: '1:578204003859:android:edbe07745666938eaad9e6',
    messagingSenderId: '578204003859',
    projectId: 'jq4b-eih-2024-inv-15307',
    storageBucket: 'jq4b-eih-2024-inv-15307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogDwScORnlXTItTgTC0cWqLLfoYuZu2U',
    appId: '1:578204003859:ios:988adab3fc66c5b5aad9e6',
    messagingSenderId: '578204003859',
    projectId: 'jq4b-eih-2024-inv-15307',
    storageBucket: 'jq4b-eih-2024-inv-15307.firebasestorage.app',
    iosBundleId: 'com.example.holaflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAogDwScORnlXTItTgTC0cWqLLfoYuZu2U',
    appId: '1:578204003859:ios:988adab3fc66c5b5aad9e6',
    messagingSenderId: '578204003859',
    projectId: 'jq4b-eih-2024-inv-15307',
    storageBucket: 'jq4b-eih-2024-inv-15307.firebasestorage.app',
    iosBundleId: 'com.example.holaflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2bW5bGLSwLl3wO4sbIeCJht4IgQ2cxSo',
    appId: '1:578204003859:web:d4d7e53c4707ff43aad9e6',
    messagingSenderId: '578204003859',
    projectId: 'jq4b-eih-2024-inv-15307',
    authDomain: 'jq4b-eih-2024-inv-15307.firebaseapp.com',
    storageBucket: 'jq4b-eih-2024-inv-15307.firebasestorage.app',
  );
}
